import { NextResponse } from 'next/server';
import { getApiKey, consumeCredit } from '@/lib/storage';

export async function POST(request: Request) {
  try {
    const apiKeyHeader = request.headers.get('x-api-key');
    
    if (!apiKeyHeader) {
      return NextResponse.json(
        { error: 'Missing x-api-key header' },
        { status: 401 }
      );
    }

    const apiKey = getApiKey(apiKeyHeader);
    
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Invalid API key' },
        { status: 401 }
      );
    }

    if (apiKey.credits <= 0) {
      return NextResponse.json(
        { error: 'No credits remaining. Please purchase more.' },
        { status: 402 }
      );
    }

    const { text, mode } = await request.json();
    
    if (!text || typeof text !== 'string') {
      return NextResponse.json(
        { error: 'text field is required' },
        { status: 400 }
      );
    }

    if (!mode || !['paraphrase', 'summarize', 'grammar', 'expand', 'simplify'].includes(mode)) {
      return NextResponse.json(
        { error: 'mode must be: paraphrase, summarize, grammar, expand, or simplify' },
        { status: 400 }
      );
    }

    // Consume credit
    const creditUsed = consumeCredit(apiKeyHeader);
    if (!creditUsed) {
      return NextResponse.json(
        { error: 'Failed to consume credit' },
        { status: 500 }
      );
    }

    // Process text based on mode (simplified demo processing)
    const result = processText(text, mode);

    return NextResponse.json({
      result,
      mode,
      creditsRemaining: apiKey.credits - 1,
    });
  } catch {
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

function processText(text: string, mode: string): string {
  // In production, this would call an AI API (OpenAI, Anthropic, etc.)
  // For demo, we apply simple transformations
  switch (mode) {
    case 'paraphrase':
      return `[Paraphrased] ${text}`;
    case 'summarize':
      return text.length > 100 ? text.substring(0, 100) + '...' : text;
    case 'grammar':
      return text.replace(/\s+/g, ' ').trim();
    case 'expand':
      return `${text}\n\n[Expanded content would be generated by AI here.]`;
    case 'simplify':
      return text.replace(/complex|sophisticated|intricate/gi, 'simple');
    default:
      return text;
  }
}
